% Generated by MATLAB(R) 23.2 (R2023b) and Communications Toolbox 23.2 (R2023b).
% Generated on: 10-Apr-2024 09:58:16

%% Generating OFDM waveform
% OFDM configuration
ofdmMod = comm.OFDMModulator('FFTLength', 16, ...
    'NumGuardBandCarriers', [6;5], ...
    'InsertDCNull', false, ...
    'CyclicPrefixLength', 16, ...
    'Windowing', false, ...
    'OversamplingFactor', 1, ...
    'NumSymbols', 100, ...
    'NumTransmitAntennas', 1, ...
    'PilotInputPort', false);

scs = 1000000;
M = 4; 	 % Modulation order
% input bit source:
in = randi([0 1], 1000, 1);

dataInput = qammod(in, M, 'gray', 'InputType', 'bit', 'UnitAveragePower', true);
ofdmInfo = info(ofdmMod);
ofdmSize = ofdmInfo.DataInputSize;
dataInput = reshape(dataInput, ofdmSize);

% Generation
waveform = ofdmMod(dataInput);

Fs = ofdmMod.FFTLength * scs * ofdmMod.OversamplingFactor; 								 % Specify the sample rate of the waveform in Hz

%% Visualize
% Spectrum Analyzer
spectrum = spectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);

% Constellation Diagram
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);
constel(waveform);
release(constel);

% OFDM Subcarrier Mapping
showResourceMapping(ofdmMod);

%% Transmit waveform over the air
masterClockRate = 16000000;
interpolationFactor = 1;
usrpTx = comm.SDRuTransmitter(Platform='B210');
usrpTx.SerialNum ='8000748';
usrpTx.CenterFrequency = 2450000000;
usrpTx.Gain = 76;
usrpTx.ChannelMapping = 1;
usrpTx.LocalOscillatorOffset = 1;
usrpTx.PPSSource = 'Internal';
usrpTx.ClockSource = 'Internal';
usrpTx.MasterClockRate = masterClockRate;
usrpTx.InterpolationFactor = interpolationFactor;
usrpTx.TransportDataType = 'int16';
usrpTx.EnableBurstMode = false;

waveform = repmat(waveform, 1, 1);

% Transmit waveform (for 10 sec):
stopTime = 10; % sec
t = 0; % sec
while t<stopTime
    usrpTx(waveform);
    t = t + length(waveform)/Fs;
end

fprintf('Transmission stopped.\n')
release(usrpTx);
